#!/bin/bash

until [[ "$memorcpu" = "mem" ]] || [[ "$memorcpu" = "cpu" ]]; do
	clear
	read -p "hello what prosess would you like to see memory or CUP usege (mem/cpu) " memorcpu
	if [[ "$memorcpu" = "mem" ]]; then
		memorcpu = mem
	elif [[ "$memorcpu" = "cpu" ]]; then
		memorcpu = cpu
	else
		echo "sorry cant do that"
		sleep 2
	fi
done

until [[ "$eh" = "poopy" ]]; do
	clear
	echo
	echo "#############################################################################################"
	echo "##################################### SCP Foundation ########################################"
	echo "#############################################################################################"
	echo
	ps aux --sort -%"$memorcpu" | head -n 9
	sleep 1
	read -p "press any key" test
done
